FROM node:22-alpine

WORKDIR /usr/app/api
COPY ./package*.json ./

RUN npm install --force

COPY . .
# RUN npm test
RUN npm run build

EXPOSE 3000

COPY entrypoint-api.sh /usr/app/api/entrypoint.sh
RUN chmod +x /usr/app/api/entrypoint.sh

ENTRYPOINT ["/usr/app/api/entrypoint.sh"]